"""add the email column

Revision ID: 790a797daede
Revises: aa9674b73abb
Create Date: 2020-09-19 17:28:24.267721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790a797daede'
down_revision = 'aa9674b73abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
